version: "3.8"

services:
  mfe-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: mfe-app
    environment:
      NODE_ENV: production
    restart: unless-stopped

networks:
  app-network:
    driver: bridge